import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/Sidebar";
import Analyzer from "@/components/Analyzer";

const inter = Inter({ variable: "--font-inter", subsets: ['latin'],weight: ["400","500", "600", "700"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${inter.variable}`}
      >

        {/* sidebar */}
        <Sidebar />
        {/* main content */}
        <Analyzer />
      </div>
    </>
  );
}
